# Generated by Django 4.1.1 on 2022-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=150)),
                ('type', models.IntegerField(choices=[(1, 'Foundation'), (2, 'Local Foundraiser'), (3, 'NGO')])),
                ('categories', models.ManyToManyField(to='donation.category')),
            ],
        ),
    ]
