# Generated by Django 4.1.1 on 2022-09-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.institution'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
