# Generated by Django 4.1.1 on 2022-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_donation_address_alter_donation_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField(null=True)),
            ],
        ),
    ]
