# Generated by Django 4.1.1 on 2022-09-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_dupa_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dupa',
        ),
    ]
